# fly.toml app configuration file generated for platform-muddy-meadow-938 on 2025-02-03T14:26:28-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'platform-muddy-meadow-938'
primary_region = 'sjc'

[build]

[env]
  AGENT_API_SECRET_AUTH = 'RCS7m2rFbrxRiiRTyW1EkYw7uosdCbIEJbOeMVZmJ9WeC8mrGHf4ZV2oWbx3DLrA'
  AWS_ACCESS_KEY_ID = 'AKIAVIOZFVR66D7D4OMY'
  AWS_BUCKET_NAME = 'chatbots-source'
  AWS_REGION = 'us-east-1'
  AWS_SECRET_ACCESS_KEY = 'yeuTeYSh78qtkb8c2/3mF1OcQeMZWdP+iy38lvdb'
  DATABASE_URL = 'postgresql://neondb_owner:npg_3j5xRsPWENCZ@ep-muddy-surf-a86tcg1f-pooler.eastus2.azure.neon.tech/neondb?sslmode=require'
  DEPLOYED_BOT_AWS_ACCESS_KEY_ID = 'AKIAVIOZFVR66M2VBFXA'
  DEPLOYED_BOT_AWS_SECRET_ACCESS_KEY = '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'
  FLY_IO_TOKEN = 'FlyV1 fm2_lJPECAAAAAAAB8NXxBCUbh4iYlfi40QeTg3sYdsGwrVodHRwczovL2FwaS5mbHkuaW8vdjGUAJLOAAz9Rx8Lk7lodHRwczovL2FwaS5mbHkuaW8vYWFhL3YxxDwfP6e1z6RTTMKW/IzQnr2aQGQMmKd7wA0RLCIuYGG6Z5Q/YXDWVFePwmo3Amv9yoeTPwO7+3wl9nge7s7ETinYab4c2hCa6larKnp+oBu8CsOOyGVZhQaZrVXh21DW2wST7of8TURXiHa4Eq6qZ9EB0ykw5w1WsjP7NKEF2uNdDWLHPVLO4w2VE7FKI8QgUvnkpfaayEv9o81gWoUNcilUEF1j+p5Rx/3MABd85TI=,fm2_lJPETinYab4c2hCa6larKnp+oBu8CsOOyGVZhQaZrVXh21DW2wST7of8TURXiHa4Eq6qZ9EB0ykw5w1WsjP7NKEF2uNdDWLHPVLO4w2VE7FKI8QQF0eq/BrCukKyz1+37imZf8O5aHR0cHM6Ly9hcGkuZmx5LmlvL2FhYS92MZgEks5nmZzQzwAAAAEjkbruF84ADJbOCpHOAAyWzgzEELRw69iT8IUnEyr0ULJeKwDEINcolC4KGJzJYckD4dMO8lEg5H/RASPiIp29oYLmJoJV'
  NEON_API_KEY = 'napi_alvbvcpk2ewgemg1rt43en3ti8vx9h0en1xnm3n04b1pugl1e80jmlkv023zkt1w'

[http_service]
  internal_port = 4444
  force_https = false
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
